services:
  - type: web
    name: hotels-scrap-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_PLACES_API_KEY
        sync: false